{% set name = "rdflib-jsonld" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eda5a42a2e09f80d4da78e32b5c684bccdf275368f1541e6b7bcddfb1382a0e0

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  skip: true  # [py < 37 and aarch64]

requirements:
  host:
    - pip
    - python
    - setuptools <58
  run:
    - python
    - rdflib >=4.2.2
    - setuptools <58

test:
  imports:
    - rdflib_jsonld

about:
  home: https://github.com/RDFLib/rdflib-jsonld
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: rdflib extension adding JSON-LD parser and serializer
  dev_url: https://github.com/RDFLib/rdflib-jsonld

extra:
  recipe-maintainers:
    - croth1
