appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: ewaBKKyOxfQ58zRbB0/jXO9DWpFc+bv5oD2X56ea2Ry3QfoNB0p3KrvZnSZRlYbPQ6b7R7NVamYBqlAQgBh30k2W1/U9dobOudNYxjZS5YSG5qDXI3Sd3l5wXZrbDNrz4zvHS5JqVHXlyrXbMtfUEs/ETHXPNS6hyKrugWrLegFEtni94k7nqopxtkT071gtLA8bfrBy2MtYIHjB7zs2DI3E7QLtK4BWYPBnjHtJx2i3pWqiU1bIylCALkbPRof+c7Pzm/N/pRLe8KM9UtXbjjHzrwzPTtMhGx2wtWiJxjIHieQxIexJNEWLr8mIAp24RMVSVXqw457cu+bFjP7gf0CpmaypNXDGQQThhIrRtKh+BE2npQJojEOwC9eO+A0+lbdec/6aOOo85t2QKGno0mPXFtkWuU1uPowUhDSh58dFAt4kY8JIMun2+t70k2/nvbMEfGY+zkCMjsKd0+GYeDj0bD0TcVWQjFWtzP1AwVKWkHhL9u1oo2958Ft5rPt/n3usPg7nYh9EWjX/sqGy6x7c12OiSlLBipo4W1HjPPi/DjkL/KsJc95cGCYmwuL5w3anHqxiKwS7AScnsId9jwvPhhDlSbrzHB2rkawuRvWb1rT/Aqqu151cAnhG7K2FCQYl/wHiUCkJ5LNTAcvv3H5snN2yGDI1GHum2n/T1bc=}
provider:
  win: azure
conda_forge_output_validation: false
